function createfigure(YMatrix1)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 22-May-2012 23:18:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 10000]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot(YMatrix1,'Parent',axes1);

% Create xlabel
xlabel({'Time Period'});

% Create ylabel
ylabel({'No. of Agents Using Strategy'});

% Create title
title('Popularity of Strategy by Period');
